-- MySQL Script generated by MySQL Workbench
-- Tue Jun  6 13:04:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MM_Store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MM_Store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MM_Store` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `MM_Store` ;

-- -----------------------------------------------------
-- Table `MM_Store`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MM_Store`.`user` (
  `uid` VARCHAR(36) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(72) NOT NULL,
  `refresh_token` VARCHAR(128) NULL DEFAULT NULL,
  `role` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MM_Store`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MM_Store`.`customer` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `contact_name` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT NULL DEFAULT NULL,
  `job_title` VARCHAR(45) NULL DEFAULT NULL,
  `company` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(256) NULL DEFAULT NULL,
  `uid` VARCHAR(36) NOT NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `fk_customer_user1_idx` (`uid` ASC) VISIBLE,
  CONSTRAINT `fk_customer_user1`
    FOREIGN KEY (`uid`)
    REFERENCES `MM_Store`.`user` (`uid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MM_Store`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MM_Store`.`product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(45) NULL DEFAULT NULL,
  `supplier_id` INT NULL DEFAULT NULL,
  `category_id` INT NULL DEFAULT NULL,
  `quantity_per_unit` VARCHAR(45) NULL DEFAULT NULL,
  `unit_price` FLOAT NOT NULL,
  `units_in_stock` INT NOT NULL,
  `sell_start_date` DATETIME NULL DEFAULT NULL,
  `sell_end_date` DATETIME NULL DEFAULT NULL,
  `discontinued_date` DATETIME NULL DEFAULT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  `unit_cost` FLOAT NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MM_Store`.`cart_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MM_Store`.`cart_item` (
  `customer_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `quantity` INT NULL DEFAULT NULL,
  INDEX `FK_Customer_Cart_idx` (`customer_id` ASC) VISIBLE,
  INDEX `FK_Product_Cart_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_Customer_Cart`
    FOREIGN KEY (`customer_id`)
    REFERENCES `MM_Store`.`customer` (`customer_id`),
  CONSTRAINT `FK_Product_Cart`
    FOREIGN KEY (`product_id`)
    REFERENCES `MM_Store`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MM_Store`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MM_Store`.`transaction` (
  `transaction_id` INT NOT NULL,
  `description` VARCHAR(256) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  `confirm` INT NULL DEFAULT NULL,
  `amount` FLOAT NULL DEFAULT NULL,
  `method` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MM_Store`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MM_Store`.`order` (
  `order_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `order_date` DATETIME NOT NULL,
  `transaction_id` INT NOT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `FK_Customer_Order_idx` (`customer_id` ASC) VISIBLE,
  INDEX `FK_Transaction_Order_idx` (`transaction_id` ASC) VISIBLE,
  CONSTRAINT `FK_Customer_Order`
    FOREIGN KEY (`customer_id`)
    REFERENCES `MM_Store`.`customer` (`customer_id`),
  CONSTRAINT `FK_Transaction_Order`
    FOREIGN KEY (`transaction_id`)
    REFERENCES `MM_Store`.`transaction` (`transaction_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MM_Store`.`product_history_cost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MM_Store`.`product_history_cost` (
  `product_id` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `standard_cost` FLOAT NULL DEFAULT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `start_date`),
  INDEX `FK_Product_ProductHistory_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_Product_ProductHistory`
    FOREIGN KEY (`product_id`)
    REFERENCES `MM_Store`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MM_Store`.`product_history_price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MM_Store`.`product_history_price` (
  `product_id` INT NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `unit_price` FLOAT NULL DEFAULT NULL,
  `modified_date` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`product_id`, `start_date`),
  INDEX `FK_Product_ProductHistoryPice_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `FK_Product_ProductHistoryPice`
    FOREIGN KEY (`product_id`)
    REFERENCES `MM_Store`.`product` (`product_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MM_Store`.`order_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MM_Store`.`order_detail` (
  `quantity` INT NULL,
  `order_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `unit_price` FLOAT NULL,
  `discount` FLOAT NULL,
  INDEX `fk_order_detail_order1_idx` (`order_id` ASC) VISIBLE,
  INDEX `fk_order_detail_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_detail_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `MM_Store`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_detail_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `MM_Store`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
